### ISSUE TITLE
Q: What is RRR card?

### ISSUE THREAD

**Issue by ajukraine** [ciscoheat/haxedci-example#2]
At https://docs.google.com/spreadsheets/d/1TSpjKUhjvP9pMRukt_mInHVbdQWsXHzFjSymQ3VyGmE/edit#gid=2 there is some entity modelling called RRR cards? What it stands for? Never heard of it.

**Comment by ciscoheat** [comment]
Hi, it's a more proper naming of CRC cards, but that was already popularized so it wasn't renamed to RRR. The answer by James Coplien in this thread gives some more info: https://www.researchgate.net/post/Do_we_consider_the_term_Responsibility_Driven_Design_RDD_and_Class_Responsibility_Assignment_CRA_the_same
